CREATE TABLE VISIT(
visit_no NUMBER(38) PRIMARY KEY,
visit_date DATE
);

CREATE SEQUENCE visit_no_seq
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE;

SELECT visit_no_seq.nextval FROM DUAL;
SELECT * FROM visit

SELECT TO_DATE(D.DAY,'YYYYMMDD') visit_date,COUNT(v.visit_no) COUNT
FROM (SELECT TO_CHAR(SYSDATE - (LEVEL - 1),'YYYYMMDD') DAY
FROM DUAL CONNECT BY LEVEL <= 7) D
LEFT OUTER JOIN visit v
ON TO_CHAR(v.visit_date,'YYYYMMDD') = D.DAY
GROUP BY TO_DATE(D.DAY,'YYYYMMDD')
ORDER BY TO_DATE(D.DAY,'YYYYMMDD')